# Generated by Django 4.2 on 2023-08-14 15:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='b2StorageFile',
            field=models.FileField(blank=True, upload_to=api.models.upload_to, verbose_name='B2 Storage File'),
        ),
    ]
