# Generated by Django 4.2.1 on 2023-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='clicks24h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='clicks30d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='clicks7d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isDairyFree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='isGlutenFree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
    ]
