# Generated by Django 4.2 on 2023-10-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_b2storagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='aditives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('PayPal', 'PayPal'), ('ApplePay', 'ApplePay'), ('GooglePay', 'GooglePay')])),
                ('tip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('items', models.ManyToManyField(to='api.item')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')])),
                ('items', models.ManyToManyField(to='api.item')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
                ('table', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.table')),
            ],
        ),
    ]
