# Generated by Django 4.2 on 2023-10-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_aditives_table_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Checkout', 'Checkout'), ('Paid', 'Paid'), ('Closed', 'Closed')]),
        ),
    ]
