# Generated by Django 4.2 on 2023-10-29 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cart_closed_at_cart_created_at_item_aditives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.table'),
        ),
    ]
