# Generated by Django 4.2 on 2023-10-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='table',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.table'),
            preserve_default=False,
        ),
    ]
