# Generated by Django 4.2 on 2023-10-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cart_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='table',
        ),
        migrations.AddField(
            model_name='table',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cart'),
        ),
    ]
