# Generated by Django 4.2 on 2023-10-23 16:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_cart_table_table_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0], size=6),
        ),
    ]
