# Generated by Django 4.2 on 2023-10-23 16:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_menu_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=6),
        ),
    ]
