# Generated by Django 4.2 on 2024-04-20 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_homepagecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopmePageRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
        migrations.AddField(
            model_name='homepagecard',
            name='row',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.hopmepagerow'),
        ),
    ]
