# Generated by Django 4.2 on 2024-05-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_item_category_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopmepagerow',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
