# Generated by Django 4.2 on 2024-05-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_hopmepagerow_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecard',
            name='text',
        ),
    ]
