# Generated by Django 4.2 on 2024-05-09 21:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_homepagecard_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='b2StorageFile',
            field=models.FileField(blank=True, upload_to=api.models.upload_background_to, verbose_name='B2 Storage File'),
        ),
        migrations.AddField(
            model_name='menu',
            name='font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='primary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='menu',
            name='secondary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
