# Generated by Django 4.2 on 2024-05-09 21:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_menu_b2storagefile_menu_font_menu_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='b2StorageFile',
            field=models.FileField(blank=True, default='https://f004.backblazeb2.com/file/platepal/background.png', upload_to=api.models.upload_background_to, verbose_name='B2 Storage File'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='primary',
            field=models.CharField(blank=True, default='#f5c636', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='secondary',
            field=models.CharField(blank=True, default='#f5c636', max_length=100),
        ),
    ]
