# Generated by Django 4.2 on 2024-05-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='table',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.table'),
        ),
    ]
