# Generated by Django 4.2 on 2024-05-20 07:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_complaint_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='b2StorageFile',
            field=models.FileField(blank=True, default='https://f004.backblazeb2.com/file/platepal/logo.png', upload_to=api.models.upload_logo_to, verbose_name='B2 Storage File'),
        ),
    ]
