# Generated by Django 4.2 on 2024-05-20 07:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_restaurant_b2storagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='b2StorageFile',
            field=models.FileField(blank=True, default=None, upload_to=api.models.upload_logo_to, verbose_name='B2 Storage File'),
        ),
    ]
