# Generated by Django 4.2 on 2024-05-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_restaurant_address_alter_restaurant_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Order',
            field=models.IntegerField(default=0),
        ),
    ]
