# Generated by Django 4.2 on 2024-05-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_category_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Order',
            new_name='order',
        ),
    ]
