# Generated by Django 4.2 on 2024-06-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='indredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
