# Generated by Django 4.2 on 2024-07-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_indredients_item_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nutriValuesLink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
